/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package data;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;
/**
 *
 * @author Fadil
 */
public class beli_cash extends javax.swing.JFrame {
private Connection con;
private Statement st;
private ResultSet rsbrg;
private String sql="";
private String kd_cash,kd_pem,kd_mot,keterangan,tanggal;
private int harga,bayar;
    /**
     * Creates new form beli_cash
     */
    public beli_cash() {
        initComponents();
        koneksitoko();
    }
    private void koneksitoko(){
        try {
            Class.forName("com.mysql.jdbc.Driver");
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_kredit_motor","root","");
            System.out.println("Koneksi berhasil");
            JOptionPane.showMessageDialog(null, "berhasil");
        }catch (Exception e) {
            System.out.println("Koneksi gagal \n"+e);
        }
    }
    private void tampildata(String aql) {
        DefaultTableModel datalist = new DefaultTableModel();
        datalist.addColumn("No");
        datalist.addColumn("Kode Cash");
        datalist.addColumn("Tanggal Cash");
        datalist.addColumn("Kode Pembeli");
        datalist.addColumn("Kode Motor");
        datalist.addColumn("Harga");
        datalist.addColumn("Bayar");
        datalist.addColumn("Keterangan");
        try {
            int i = 1;
            st=con.createStatement();
            rsbrg=st.executeQuery("select * from beli_cash");
            while (rsbrg.next()) {
                datalist.addRow(new Object[]{
                    (""+i++),rsbrg.getString(1),
                    rsbrg.getString(2),rsbrg.getString(3),
                    rsbrg.getString(4),rsbrg.getString(5),
                    rsbrg.getString(6),rsbrg.getString(7),
            });
            gridBarang.setModel(datalist);
            }
          } catch (Exception e) {
               JOptionPane.showMessageDialog(null, "Gagal tampil \n"+e.getMessage());
        }
    }
    public void ulang() {
        txtKodecash.setText("");
        txtKodepembeli.setText("");
        txtKodemotor.setText("");
        txtHarga.setText("");
        txtBayar.setText("");
        txtKeterangan.setText("");
        dtcTanggalcash.setDate(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCalendar1 = new com.toedter.calendar.JCalendar();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtKodecash = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtKodepembeli = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtKodemotor = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtHarga = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtBayar = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btnTambah = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        gridBarang = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        dtcTanggalcash = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        txtKeterangan = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Data Pembelian Cash");

        jPanel1.setBackground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );

        jLabel2.setText("Kode Cash");

        txtKodecash.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtKodecashKeyPressed(evt);
            }
        });

        jLabel3.setText("Tanggal Cash");

        jLabel4.setText("Kode Pembeli");

        txtKodepembeli.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtKodepembeliCaretUpdate(evt);
            }
        });
        txtKodepembeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKodepembeliActionPerformed(evt);
            }
        });
        txtKodepembeli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtKodepembeliKeyPressed(evt);
            }
        });

        jLabel5.setText("Kode Motor");

        txtKodemotor.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtKodemotorCaretUpdate(evt);
            }
        });

        jLabel6.setText("Harga");

        jLabel7.setText("Bayar");

        jPanel2.setBackground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        gridBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Kode Cash", "Tanggal Cash", "Kode Pembeli", "Kode Motor", "Harga", "Bayar"
            }
        ));
        jScrollPane1.setViewportView(gridBarang);

        jPanel4.setBackground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );

        jLabel8.setText("Keterangan");

        txtKeterangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKeteranganActionPerformed(evt);
            }
        });

        txtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel4)
                        .addGap(31, 31, 31)
                        .addComponent(txtKodepembeli, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel5)
                        .addGap(39, 39, 39)
                        .addComponent(txtKodemotor, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel6)
                        .addGap(65, 65, 65)
                        .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btnTambah)
                        .addGap(39, 39, 39)
                        .addComponent(btnEdit)
                        .addGap(49, 49, 49)
                        .addComponent(btnHapus)
                        .addGap(47, 47, 47)
                        .addComponent(btnReset))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dtcTanggalcash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtKodecash, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtBayar, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                            .addComponent(txtKeterangan))))
                .addGap(10, 10, 10))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel2))
                            .addComponent(txtKodecash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addComponent(jLabel3))
                    .addComponent(dtcTanggalcash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel4))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtKodepembeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel5))
                    .addComponent(txtKodemotor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(txtBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(46, 46, 46)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnTambah)
                            .addComponent(btnEdit)
                            .addComponent(btnHapus)
                            .addComponent(btnReset))
                        .addGap(37, 37, 37)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtKeterangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        kd_cash=String.valueOf(txtKodecash.getText());
            kd_pem=String.valueOf(txtKodepembeli.getText());
            kd_mot=String.valueOf(txtKodemotor.getText());
            harga=Integer.parseInt(txtHarga.getText());
            bayar=Integer.parseInt(txtBayar.getText());
            keterangan=String.valueOf(txtKeterangan.getText());
        String tampilan = "yyyy-MM-dd";
        SimpleDateFormat fm = new SimpleDateFormat(tampilan);
        tanggal= String.valueOf(fm.format(dtcTanggalcash.getDate()));
            try {
                sql = " insert into beli_cash(kd_cash,tgl_cash,kd_pembeli,kd_motor,harga,bayar,keterangan)values"
    + "('"+kd_cash + "', '" + tanggal + "','"+kd_pem+"','"+kd_mot+"','"+harga+"','"+bayar+"','"+keterangan+"')";
                st=con.createStatement();
                st.execute(sql);
                tampildata("select * from beli_cash");
                JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Data gagal disimpan");
            }
            ulang();
    }//GEN-LAST:event_btnTambahActionPerformed

    private void txtKeteranganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKeteranganActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtKeteranganActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        kd_cash=String.valueOf(txtKodecash.getText());
        kd_pem=String.valueOf(txtKodepembeli.getText());
        kd_mot=String.valueOf(txtKodepembeli.getText());
        harga=Integer.parseInt(txtHarga.getText());
        bayar=Integer.parseInt(txtBayar.getText());
        keterangan=String.valueOf(txtKeterangan.getText());
        String tampilan = "yyyy-MM-dd";
        SimpleDateFormat fm = new SimpleDateFormat(tampilan);
        tanggal= String.valueOf(fm.format(dtcTanggalcash.getDate()));
        if (JOptionPane.showConfirmDialog(this, "Apakah data ini mau diubah ?", "konfirmasi",
                JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE)==
                JOptionPane.YES_OPTION) {
        try {
            sql = "update beli_cash set tgl_cash='"+tanggal+"', kd_pembeli='"+kd_pem+"',kd_motor='"+kd_mot+"',harga='"+harga+"',bayar='"+bayar+"',keterangan='"+keterangan+"' where kd_cash='"+kd_cash+"'";
            st=con.createStatement();
            st.execute(sql);
            tampildata("select*from beli_cash");
            JOptionPane.showMessageDialog(null, "data berhasil diubah");
            ulang();
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Data gagal diubah \n"+e.getMessage());
        }
        
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        kd_cash=String.valueOf(txtKodecash.getText());
        if (JOptionPane.showConfirmDialog(this, "Apakah anda yakin menghapus data ini", "Konfirmasi",
                JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE)==
                JOptionPane.YES_OPTION)
        {
            try {
                sql="delete from beli_cash where kd_cash='"+kd_cash+"'";
                st = con.createStatement();
                st.execute(sql);
                tampildata("select*from beli_cash");
                JOptionPane.showMessageDialog(null, "data berhasil dihapus");
                ulang();
            }catch (Exception e){
                JOptionPane.showMessageDialog(null, "data gagal dihapus \n"+e.getMessage());
            }
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        ulang();
    }//GEN-LAST:event_btnResetActionPerformed

    private void txtKodecashKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKodecashKeyPressed
        // TODO add your handling code here:
        kd_cash=txtKodecash.getText();
            int tekantekanan=evt.getKeyCode();
            if (tekantekanan==10) {
                try {
                    sql="select*from beli_cash where kd_cash='"+kd_cash+"'";
                    st=con.createStatement();
                    rsbrg=st.executeQuery(sql);
                    while (rsbrg.next()) {
                    dtcTanggalcash.setDate(rsbrg.getDate(2));
                    txtKodepembeli.setText(rsbrg.getString(3));
                    txtKodemotor.setText(rsbrg.getString(4));
                    txtHarga.setText(rsbrg.getString(5));
                    txtBayar.setText(rsbrg.getString(6));
                    txtKeterangan.setText(rsbrg.getString(7));
                    
                    JOptionPane.showMessageDialog(null, "Ehh nemu");
                    btnTambah.enable(false);
                    btnEdit.enable(false);
            } 
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gak nemu \n"+e.getMessage());
            }
       }
    }//GEN-LAST:event_txtKodecashKeyPressed

    private void txtKodepembeliKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKodepembeliKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKodepembeliKeyPressed

    private void txtKodepembeliCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtKodepembeliCaretUpdate
        // TODO add your handling code here:
        kd_pem = txtKodepembeli.getText();
        try {
            sql="select * from pembeli where kd_pembeli = '"+kd_pem+"'";
            st=con.createStatement();
            rsbrg=st.executeQuery(sql);
            while(rsbrg.next()) {
                txtNama.setText(rsbrg.getString(2));
                btnTambah.enable(false);
                btnEdit.enable(false);
            } 
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gak nemu \n"+e.getMessage());
            }
    }//GEN-LAST:event_txtKodepembeliCaretUpdate

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaActionPerformed

    private void txtKodepembeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKodepembeliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKodepembeliActionPerformed

    private void txtKodemotorCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtKodemotorCaretUpdate
        // TODO add your handling code here:
        kd_mot = txtKodemotor.getText();
        try {
            sql="select * from motor where kd_motor = '"+kd_mot+"'";
            st=con.createStatement();
            rsbrg=st.executeQuery(sql);
            while(rsbrg.next()) {
                txtHarga.setText(rsbrg.getString(8));
                btnTambah.enable(false);
                btnEdit.enable(false);
            } 
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gak nemu \n"+e.getMessage());
            }
    }//GEN-LAST:event_txtKodemotorCaretUpdate

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(beli_cash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(beli_cash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(beli_cash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(beli_cash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new beli_cash().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnTambah;
    private com.toedter.calendar.JDateChooser dtcTanggalcash;
    private javax.swing.JTable gridBarang;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtBayar;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtKeterangan;
    private javax.swing.JTextField txtKodecash;
    private javax.swing.JTextField txtKodemotor;
    private javax.swing.JTextField txtKodepembeli;
    private javax.swing.JTextField txtNama;
    // End of variables declaration//GEN-END:variables
}
