/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package data;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Fadil
 */
public class motor extends javax.swing.JFrame {
private Connection con;
private Statement st;
private ResultSet rsbrg;
private String sql;
private String kode,nama,merk,jenis,warna;
private int nomes,tahun,harga;


    /**
     * Creates new form motor
     */
    public motor() {
        initComponents();
        koneksitoko();
    }
    private void koneksitoko(){
        try {
            Class.forName("com.mysql.jdbc.Driver");
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_kredit_motor","root","");
            System.out.println("Koneksi berhasil");
            JOptionPane.showMessageDialog(null, "berhasil");
        }catch (Exception e) {
            System.out.println("Koneksi gagal \n"+e);
        }
    }
    private void tampildata(String aql) {
        DefaultTableModel datalist = new DefaultTableModel();
        datalist.addColumn("No");
        datalist.addColumn("Kode Motor");
        datalist.addColumn("No Mesin");
        datalist.addColumn("Merek");
        datalist.addColumn("Jenis");
        datalist.addColumn("Warna");
        datalist.addColumn("Harga");
        datalist.addColumn("Tahun");
        try {
            int i = 1;
            st=con.createStatement();
            rsbrg=st.executeQuery("select * from motor");
            while (rsbrg.next()) {
                datalist.addRow(new Object[]{
                    (""+i++),rsbrg.getString(1),
                    rsbrg.getString(2),rsbrg.getString(3),
                    rsbrg.getString(4),rsbrg.getString(5),
                    rsbrg.getString(6),rsbrg.getString(7),
                    rsbrg.getString(8)
            });
            gridBarang.setModel(datalist);
            }
          } catch (Exception e) {
               JOptionPane.showMessageDialog(null, "Gagal tampil \n"+e.getMessage());
        }
    }
    public void ulang() {
        txtKodemotor.setText("");
        txtNomesin.setText("");
        txtNamamotor.setText("");
        txtWarna.setText("");
        txtHarga.setText("");
        txtTahun.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtKodemotor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNomesin = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cmbMerek = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        txtNamamotor = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cmbJenis = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        txtWarna = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtHarga = new javax.swing.JTextField();
        btnTambah = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        gridBarang = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        txtTahun = new javax.swing.JTextField();
        btnNext = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Data Motor");

        jLabel2.setText("Kode Motor");

        jPanel1.setBackground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );

        txtKodemotor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKodemotorActionPerformed(evt);
            }
        });
        txtKodemotor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtKodemotorKeyPressed(evt);
            }
        });

        jLabel3.setText("No. Mesin");

        jLabel4.setText(" Merek");

        cmbMerek.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Yamaha", "Honda", "Kawasaki", "Suzuki" }));

        jLabel5.setText("Nama Motor");

        jLabel6.setText("Jenis");

        cmbJenis.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Matic", "Bebek" }));

        jLabel7.setText("Warna");

        jLabel8.setText("Harga");

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );

        gridBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Kode Motor", "No. Mesin", "Merek", "Nama Motor", "Jenis", "Warna", "Hargal", "Tahun"
            }
        ));
        jScrollPane1.setViewportView(gridBarang);

        jLabel9.setText("Tahun");

        txtTahun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTahunActionPerformed(evt);
            }
        });

        btnNext.setText("Next");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(150, 150, 150))
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnTambah)
                        .addGap(39, 39, 39)
                        .addComponent(btnEdit)
                        .addGap(31, 31, 31)
                        .addComponent(btnHapus)
                        .addGap(44, 44, 44)
                        .addComponent(btnReset)
                        .addGap(28, 28, 28)
                        .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTahun, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cmbMerek, 0, 89, Short.MAX_VALUE)
                                .addComponent(txtNomesin)
                                .addComponent(txtKodemotor)
                                .addComponent(txtNamamotor)
                                .addComponent(cmbJenis, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtWarna)
                                .addComponent(txtHarga)))))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(10, 10, 10)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtKodemotor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNomesin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(cmbMerek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txtNamamotor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(cmbJenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(txtWarna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtTahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambah)
                    .addComponent(btnEdit)
                    .addComponent(btnHapus)
                    .addComponent(btnReset)
                    .addComponent(btnNext))
                .addGap(8, 8, 8)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtKodemotorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKodemotorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKodemotorActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        kode=String.valueOf(txtKodemotor.getText());
            nomes=Integer.parseInt(txtNomesin.getText());
            merk=cmbMerek.getItemAt(cmbMerek.getSelectedIndex()).toString();
            jenis=cmbJenis.getItemAt(cmbJenis.getSelectedIndex()).toString();
            nama=String.valueOf(txtNamamotor.getText());
            tahun=Integer.parseInt(txtTahun.getText());
            harga=Integer.parseInt(txtHarga.getText());
            warna=String.valueOf(txtWarna.getText());
            
            try {
                sql = " insert into motor(kd_motor,no_mesin,merk,jenis,nama,tahun_pembuatan,warna, harga)values"
    + "('"+kode + "', '" + nomes + "','"+merk+"','"+jenis+"','"+nama+"','"+tahun+"','"+warna+"','"+harga+"')";
                st=con.createStatement();
                st.execute(sql);
                tampildata("select * from motor");
                JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Data gagal disimpan");
            }
            ulang();
    }//GEN-LAST:event_btnTambahActionPerformed

    private void txtTahunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTahunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTahunActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        kode=String.valueOf(txtKodemotor.getText());
        nomes=Integer.parseInt(txtNomesin.getText());
        merk=cmbMerek.getItemAt(cmbMerek.getSelectedIndex()).toString();
        jenis=cmbJenis.getItemAt(cmbJenis.getSelectedIndex()).toString();
        nama=String.valueOf(txtNamamotor.getText());
        tahun=Integer.parseInt(txtTahun.getText());
        harga=Integer.parseInt(txtHarga.getText());
        warna=String.valueOf(txtWarna.getText());
        if (JOptionPane.showConfirmDialog(this, "Apakah data ini mau diubah ?", "konfirmasi",
                JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE)==
                JOptionPane.YES_OPTION) {
        try {
            sql = "update motor set no_mesin='"+nomes+"', merk='"+merk+"',jenis='"+jenis+"',nama='"+nama+"',tahun_pembuatan='"+tahun+"',warna='"+warna+"',harga='"+harga+"' where kd_motor='"+kode+"'";
            st=con.createStatement();
            st.execute(sql);
            tampildata("select*from motor");
            JOptionPane.showMessageDialog(null, "data berhasil diubah");
            ulang();
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Data gagal diubah \n"+e.getMessage());
        }
        
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        kode=String.valueOf(txtKodemotor.getText());
        if (JOptionPane.showConfirmDialog(this, "Apakah anda yakin menghapus data ini", "Konfirmasi",
                JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE)==
                JOptionPane.YES_OPTION)
        {
            try {
                sql="delete from motor where kd_motor='"+kode+"'";
                st = con.createStatement();
                st.execute(sql);
                tampildata("select*from motor");
                JOptionPane.showMessageDialog(null, "data berhasil dihapus");
                ulang();
            }catch (Exception e){
                JOptionPane.showMessageDialog(null, "data gagal dihapus \n"+e.getMessage());
            }
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void txtKodemotorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKodemotorKeyPressed
        // TODO add your handling code here:
        kode=txtKodemotor.getText();
        try {
            sql="select*from motor where kd_motor='"+kode+"'";
            st=con.createStatement();
            rsbrg=st.executeQuery(sql);
            while (rsbrg.next()) {
                txtNomesin.setText(rsbrg.getString(2));
                cmbMerek.setSelectedItem(rsbrg.getString(3));
                cmbJenis.setSelectedItem(rsbrg.getString(4));
                txtNamamotor.setText(rsbrg.getString(5));
                txtTahun.setText(rsbrg.getString(6));
                txtWarna.setText(rsbrg.getString(7));
                txtHarga.setText(rsbrg.getString(8));
                JOptionPane.showMessageDialog(null, "Ehh nemu");
                btnTambah.enable(false);
                btnEdit.enable(false);
            } 
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gak nemu \n"+e.getMessage());
        }
    }//GEN-LAST:event_txtKodemotorKeyPressed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        ulang();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
        beli_cash x = new beli_cash();
        x.show();
        dispose();
    }//GEN-LAST:event_btnNextActionPerformed

    /**
     * @param args the commmand line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(motor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(motor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(motor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(motor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new motor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnTambah;
    private javax.swing.JComboBox cmbJenis;
    private javax.swing.JComboBox cmbMerek;
    private javax.swing.JTable gridBarang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtKodemotor;
    private javax.swing.JTextField txtNamamotor;
    private javax.swing.JTextField txtNomesin;
    private javax.swing.JTextField txtTahun;
    private javax.swing.JTextField txtWarna;
    // End of variables declaration//GEN-END:variables
}
