/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package data;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;
/**
 *
 * @author Fadil
 */
public class beli_kredit extends javax.swing.JFrame {
private Connection con;
private Statement st;
private ResultSet rsbrg;
private String sql="";
private String kd_kredit,kd_pem,kd_mot,nama_pembeli,nama_motor,tanggal,ktp,lama,keterangan;
private int harga,uangmuka,sisa,cicilan;
    /**
     * Creates new form beli_kredit
     */
    public beli_kredit() {
        initComponents();
        koneksitoko();
    }
    private void koneksitoko(){
        try {
            Class.forName("com.mysql.jdbc.Driver");
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_kredit_motor","root","");
            System.out.println("Koneksi berhasil");
            JOptionPane.showMessageDialog(null, "berhasil");
        }catch (Exception e) {
            System.out.println("Koneksi gagal \n"+e);
        }
    }
    private void tampildata(String aql) {
        DefaultTableModel datalist = new DefaultTableModel();
        datalist.addColumn("No");
        datalist.addColumn("Kode Kredit");
        datalist.addColumn("Tanggal Pengkreditan");
        datalist.addColumn("Kode Motor");
        datalist.addColumn("Kode Pembeli");
        datalist.addColumn("Uang Muka");
        datalist.addColumn("Lama cicilan");
        datalist.addColumn("Cicilan");
        datalist.addColumn("Sisa");
        datalist.addColumn("Keterangan");
        try {
            int i = 1;
            st=con.createStatement();
            rsbrg=st.executeQuery("select * from beli_kredit");
            while (rsbrg.next()) {
                datalist.addRow(new Object[]{
                    (""+i++),rsbrg.getString(1),
                    rsbrg.getString(2),rsbrg.getString(3),
                    rsbrg.getString(4),rsbrg.getString(5),
                    rsbrg.getString(6),rsbrg.getString(7),
                    rsbrg.getString(8),rsbrg.getString(9)
            });
            gridBarang.setModel(datalist);
            }
          } catch (Exception e) {
               JOptionPane.showMessageDialog(null, "Gagal tampil \n"+e.getMessage());
        }
    }
    public void ulang() {
        txtKodekredit.setText("");
        jdcTanggalkredit.setDate(null);
        txtKodepembeli.setText("");
        txtNama.setText("");
        txtNoktp.setText("");
        txtKodemotor.setText("");
        txtNamamotor.setText("");
        txtHarga.setText("");
        txtUangmuka.setText("");
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtKodekredit = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtKodepembeli = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtNoktp = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtKodemotor = new javax.swing.JTextField();
        txtNamamotor = new javax.swing.JTextField();
        txtHarga = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        cmbLama = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        txtUangmuka = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtCicilanperbulan = new javax.swing.JTextField();
        txtSisa = new javax.swing.JTextField();
        txtStatusketerangan = new javax.swing.JTextField();
        btnCek = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnTambah = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        gridBarang = new javax.swing.JTable();
        jdcTanggalkredit = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Data Kredit");

        jPanel1.setBackground(new java.awt.Color(51, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 621, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );

        jLabel2.setText("Kode Kredit");

        txtKodekredit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtKodekreditKeyPressed(evt);
            }
        });

        jLabel3.setText("Tanggal Kredit");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Data Pembeli");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Pilihan Pengambilan");

        jLabel6.setText("Kode Pembeli");

        txtKodepembeli.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtKodepembeliCaretUpdate(evt);
            }
        });
        txtKodepembeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKodepembeliActionPerformed(evt);
            }
        });
        txtKodepembeli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtKodepembeliKeyPressed(evt);
            }
        });

        jLabel7.setText("Nama Pembeli");

        jLabel8.setText("No.KTP");

        txtNoktp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNoktpActionPerformed(evt);
            }
        });

        jLabel9.setText("Kode Motor");

        txtKodemotor.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtKodemotorCaretUpdate(evt);
            }
        });
        txtKodemotor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtKodemotorKeyPressed(evt);
            }
        });

        txtHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHargaActionPerformed(evt);
            }
        });

        jLabel10.setText("Nama Motor");

        jLabel11.setText("Harga");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Data Motor");

        jLabel13.setText("Lama Cicilan");

        cmbLama.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "12", "24", "36" }));
        cmbLama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbLamaActionPerformed(evt);
            }
        });

        jLabel14.setText("Uang Muka");

        txtUangmuka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUangmukaActionPerformed(evt);
            }
        });

        jLabel15.setText("*Cicilan Perbulan");

        jLabel16.setText("*Sisa");

        jLabel17.setText("*Status Keterangan");

        txtSisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSisaActionPerformed(evt);
            }
        });

        btnCek.setText("Cek");
        btnCek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCekActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(51, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 621, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        gridBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(gridBarang);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(278, 278, 278)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel2)
                        .addGap(39, 39, 39)
                        .addComponent(txtKodekredit, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(106, 106, 106)
                        .addComponent(jLabel3)
                        .addGap(14, 14, 14)
                        .addComponent(jdcTanggalkredit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(209, 209, 209)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel6))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(105, 105, 105)
                                .addComponent(txtNoktp, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel8))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(105, 105, 105)
                                .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(105, 105, 105)
                                .addComponent(txtKodepembeli, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel7)))
                        .addGap(106, 106, 106)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtKodemotor, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNamamotor, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(35, 35, 35)
                                .addComponent(cmbLama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(40, 40, 40)
                                .addComponent(txtUangmuka, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addComponent(btnCek)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addComponent(jLabel16))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(238, 238, 238)
                                .addComponent(txtCicilanperbulan, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(238, 238, 238)
                                .addComponent(txtSisa, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addComponent(jLabel15))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addComponent(jLabel17))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(238, 238, 238)
                                .addComponent(txtStatusketerangan, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(btnTambah)
                        .addGap(44, 44, 44)
                        .addComponent(btnEdit)
                        .addGap(38, 38, 38)
                        .addComponent(btnHapus)
                        .addGap(32, 32, 32)
                        .addComponent(btnReset))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addGap(11, 11, 11)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txtKodekredit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel3))
                    .addComponent(jdcTanggalkredit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel12)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel6)
                        .addGap(52, 52, 52)
                        .addComponent(txtNoktp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(txtKodepembeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel9)
                        .addGap(17, 17, 17)
                        .addComponent(jLabel10)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel11))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(txtKodemotor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(txtNamamotor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel13))
                            .addComponent(cmbLama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel14))
                            .addComponent(txtUangmuka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addComponent(btnCek))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jLabel16))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(txtCicilanperbulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(txtSisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel15))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jLabel17))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(txtStatusketerangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTambah)
                    .addComponent(btnEdit)
                    .addComponent(btnHapus)
                    .addComponent(btnReset))
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtKodepembeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKodepembeliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKodepembeliActionPerformed

    private void txtNoktpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNoktpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNoktpActionPerformed

    private void txtHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHargaActionPerformed

    private void cmbLamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbLamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbLamaActionPerformed

    private void txtUangmukaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUangmukaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUangmukaActionPerformed

    private void txtSisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSisaActionPerformed

    private void btnCekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCekActionPerformed
        // TODO add your handling code here:
        harga=Integer.parseInt(txtHarga.getText());
        uangmuka=Integer.parseInt(txtUangmuka.getText());
        sisa=harga-uangmuka;
        txtSisa.setText(String.valueOf(sisa));
        
        lama=String.valueOf(cmbLama.getSelectedItem());
        harga=Integer.parseInt(String.valueOf(txtHarga.getText()));
        if (lama == "12") {
            cicilan=harga/12;
        } 
        else if (lama=="24") {
            cicilan=harga/24;
        }
        else if (lama=="36") {
            cicilan=harga/36;
        }
        txtCicilanperbulan.setText(String.valueOf(cicilan));
        
        if (sisa > 0) {
            keterangan ="belum lunas";
        } else {
            keterangan="lunas";
        }
        txtStatusketerangan.setText(keterangan);
    }//GEN-LAST:event_btnCekActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        kd_kredit=String.valueOf(txtKodekredit.getText());
            kd_pem=String.valueOf(txtKodepembeli.getText());
            kd_mot=String.valueOf(txtKodemotor.getText());
            harga=Integer.parseInt(txtHarga.getText());
            ktp=String.valueOf(txtNoktp.getText());
            nama_motor=String.valueOf(txtNamamotor.getText());
            sisa=Integer.parseInt(txtSisa.getText());
            cicilan=Integer.parseInt(txtCicilanperbulan.getText());
            uangmuka=Integer.parseInt(txtUangmuka.getText());
            lama=cmbLama.getItemAt(cmbLama.getSelectedIndex()).toString();
            keterangan=String.valueOf(txtStatusketerangan.getText());
        String tampilan = "yyyy-MM-dd";
        SimpleDateFormat fm = new SimpleDateFormat(tampilan);
        tanggal= String.valueOf(fm.format(jdcTanggalkredit.getDate()));
            try {
                sql = " insert into beli_kredit(kd_kredit,tgl_kredit,kd_pembeli,kd_motor,uang_muka,lama_cicilan,cicilan_per_bulan,sisa,keterangan)values"
    + "('"+kd_kredit + "', '" + tanggal + "','"+kd_pem+"','"+kd_mot+"','"+uangmuka+"','"+lama+"','"+cicilan+"','"+sisa+"','"+keterangan+"')";
                st=con.createStatement();
                st.execute(sql);
                tampildata("select * from beli_kredit");
                JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Data gagal disimpan");
            }
            ulang();
    }//GEN-LAST:event_btnTambahActionPerformed

    private void txtKodepembeliKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKodepembeliKeyPressed
        // TODO add your handling code here:
        kd_pem = txtKodepembeli.getText();
        try {
            sql="select * from pembeli where kd_pembeli = '"+kd_pem+"'";
            st=con.createStatement();
            rsbrg=st.executeQuery(sql);
            while(rsbrg.next()) {
                txtNama.setText(rsbrg.getString(2));
                txtNoktp.setText(rsbrg.getString(3));
                btnTambah.enable(false);
                btnEdit.enable(false);
            } 
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gak nemu \n"+e.getMessage());
            }       
    }//GEN-LAST:event_txtKodepembeliKeyPressed

    private void txtKodemotorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKodemotorKeyPressed
        // TODO add your handling code here:
        kd_mot = txtKodemotor.getText();
        try {
            sql="select * from motor where kd_motor = '"+kd_mot+"'";
            st=con.createStatement();
            rsbrg=st.executeQuery(sql);
            while(rsbrg.next()) {
                txtNamamotor.setText(rsbrg.getString(5));
                txtHarga.setText(rsbrg.getString(8));
                btnTambah.enable(false);
                btnEdit.enable(false);
            } 
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gak nemu \n"+e.getMessage());
            }
    }//GEN-LAST:event_txtKodemotorKeyPressed

    private void txtKodepembeliCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtKodepembeliCaretUpdate
        // TODO add your handling code here:
        kd_pem = txtKodepembeli.getText();
        try {
            sql="select * from pembeli where kd_pembeli = '"+kd_pem+"'";
            st=con.createStatement();
            rsbrg=st.executeQuery(sql);
            while(rsbrg.next()) {
                txtNama.setText(rsbrg.getString(2));
                txtNoktp.setText(rsbrg.getString(3));
                btnTambah.enable(false);
                btnEdit.enable(false);
            } 
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gak nemu \n"+e.getMessage());
            }      
    }//GEN-LAST:event_txtKodepembeliCaretUpdate

    private void txtKodemotorCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtKodemotorCaretUpdate
        // TODO add your handling code here:
        kd_mot = txtKodemotor.getText();
        try {
            sql="select * from motor where kd_motor = '"+kd_mot+"'";
            st=con.createStatement();
            rsbrg=st.executeQuery(sql);
            while(rsbrg.next()) {
                txtNamamotor.setText(rsbrg.getString(5));
                txtHarga.setText(rsbrg.getString(8));
                btnTambah.enable(false);
                btnEdit.enable(false);
            } 
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gak nemu \n"+e.getMessage());
            }
    }//GEN-LAST:event_txtKodemotorCaretUpdate

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        kd_kredit=String.valueOf(txtKodekredit.getText());
            kd_pem=String.valueOf(txtKodepembeli.getText());
            kd_mot=String.valueOf(txtKodemotor.getText());
            harga=Integer.parseInt(txtHarga.getText());
            ktp=String.valueOf(txtNoktp.getText());
            nama_motor=String.valueOf(txtNamamotor.getText());
            sisa=Integer.parseInt(txtSisa.getText());
            cicilan=Integer.parseInt(txtCicilanperbulan.getText());
            uangmuka=Integer.parseInt(txtUangmuka.getText());
            lama=cmbLama.getItemAt(cmbLama.getSelectedIndex()).toString();
            keterangan=String.valueOf(txtStatusketerangan.getText());
        String tampilan = "yyyy-MM-dd";
        SimpleDateFormat fm = new SimpleDateFormat(tampilan);
        tanggal= String.valueOf(fm.format(jdcTanggalkredit.getDate()));
        if (JOptionPane.showConfirmDialog(this, "Apakah data ini mau diubah ?", "konfirmasi",
                JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE)==
                JOptionPane.YES_OPTION) {
        try {
            sql = "update beli_kredit set tgl_kredit='"+tanggal+"', kd_pembeli='"+kd_pem+"',kd_motor='"+kd_mot+"',uang_muka='"+uangmuka+"',lama_cicilan='"+lama+"',cicilan_per_bulan='"+cicilan+"',sisa='"+sisa+"',keterangan='"+keterangan+"' where kd_kredit='"+kd_kredit+"'";
            st=con.createStatement();
            st.execute(sql);
            tampildata("select*from beli_kredit");
            JOptionPane.showMessageDialog(null, "data berhasil diubah");
            ulang();
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Data gagal diubah \n"+e.getMessage());
        }
        
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        kd_kredit=String.valueOf(txtKodekredit.getText());
        if (JOptionPane.showConfirmDialog(this, "Apakah anda yakin menghapus data ini", "Konfirmasi",
                JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE)==
                JOptionPane.YES_OPTION)
        {
            try {
                sql="delete from beli_kredit where kd_kredit='"+kd_kredit+"'";
                st = con.createStatement();
                st.execute(sql);
                tampildata("select*from beli_kredit");
                JOptionPane.showMessageDialog(null, "data berhasil dihapus");
                ulang();
            }catch (Exception e){
                JOptionPane.showMessageDialog(null, "data gagal dihapus \n"+e.getMessage());
            }
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        ulang();
    }//GEN-LAST:event_btnResetActionPerformed

    private void txtKodekreditKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKodekreditKeyPressed
        // TODO add your handling code here:
        kd_kredit = txtKodekredit.getText();
        try {
            sql="select * from pembeli where kd_kredit = '"+kd_kredit+"'";
            st=con.createStatement();
            rsbrg=st.executeQuery(sql);
            while(rsbrg.next()) {
                txtNama.setText(rsbrg.getString(2));
                btnTambah.enable(false);
                btnEdit.enable(false);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gak nemu \n"+e.getMessage());
            }
    }//GEN-LAST:event_txtKodekreditKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(beli_kredit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(beli_kredit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(beli_kredit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(beli_kredit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new beli_kredit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCek;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnTambah;
    private javax.swing.JComboBox cmbLama;
    private javax.swing.JTable gridBarang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser jdcTanggalkredit;
    private javax.swing.JTextField txtCicilanperbulan;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtKodekredit;
    private javax.swing.JTextField txtKodemotor;
    private javax.swing.JTextField txtKodepembeli;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNamamotor;
    private javax.swing.JTextField txtNoktp;
    private javax.swing.JTextField txtSisa;
    private javax.swing.JTextField txtStatusketerangan;
    private javax.swing.JTextField txtUangmuka;
    // End of variables declaration//GEN-END:variables
}
